apiVersion: v1
kind: Service
metadata:
  name: sws-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: sws-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sws-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sws-backend
  template:
    metadata:
      labels:
        app: sws-backend
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.7
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: I could be pushing my dockerfile image here but dont have the infra setup yet
